language: go
sudo: false
matrix:
  include:
    - go: 1.x
      env: LATEST=true
    - go: tip
  allow_failures:
    - go: tip

before_install:
  - go get -t -v ./...
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service=travis-ci

# NOTE: temporarily disabled automatic uploading of releases - the releases are supposed to be stable, so manual deploys are doable, and the automated pipeline is only causing issues
#deploy:
#  provider: script
#  script: bash deploy.sh
#  on:
#    branch: master
