language: go
sudo: false
matrix:
  include:
    - go: 1.x

before_install:
  - go get -t -v ./... # move to go mod soon
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service=travis-ci

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux AND $TRAVIS_BRANCH = master