// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-1]
	_ = x[EOF-2]
	_ = x[Comment-3]
	_ = x[EOL-4]
	_ = x[Identifier-5]
	_ = x[Integer-6]
	_ = x[Float-7]
	_ = x[String-8]
	_ = x[Assign-9]
	_ = x[Plus-10]
	_ = x[Minus-11]
	_ = x[Bang-12]
	_ = x[Asterisk-13]
	_ = x[Slash-14]
	_ = x[LessThan-15]
	_ = x[GreaterThan-16]
	_ = x[Equal-17]
	_ = x[NotEqual-18]
	_ = x[Comma-19]
	_ = x[SemiColon-20]
	_ = x[LParen-21]
	_ = x[RParen-22]
	_ = x[LBrace-23]
	_ = x[RBrace-24]
	_ = x[LBracket-25]
	_ = x[RBracket-26]
	_ = x[Function-27]
	_ = x[Var-28]
	_ = x[True-29]
	_ = x[False-30]
	_ = x[Nil-31]
	_ = x[If-32]
	_ = x[Else-33]
	_ = x[While-34]
	_ = x[Return-35]
	_ = x[Exit-36]
}

const _TokenType_name = "IllegalEOFCommentEOLIdentifierIntegerFloatStringAssignPlusMinusBangAsteriskSlashLessThanGreaterThanEqualNotEqualCommaSemiColonLParenRParenLBraceRBraceLBracketRBracketFunctionVarTrueFalseNilIfElseWhileReturnExit"

var _TokenType_index = [...]uint8{0, 7, 10, 17, 20, 30, 37, 42, 48, 54, 58, 63, 67, 75, 80, 88, 99, 104, 112, 117, 126, 132, 138, 144, 150, 158, 166, 174, 177, 181, 186, 189, 191, 195, 200, 206, 210}

func (i TokenType) String() string {
	i -= 1
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
